-- MySQL Script generated by MySQL Workbench
-- Tue Mar  2 18:05:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library_bd` DEFAULT CHARACTER SET utf8 ;
USE `library_bd` ;

-- -----------------------------------------------------
-- Table `library_bd`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_bd`.`authors` (
  `a_id` INT NOT NULL AUTO_INCREMENT,
  `a_name` VARCHAR(60) NOT NULL,
  `a_surname` VARCHAR(60) NOT NULL,
  `a_rating` FLOAT NOT NULL,
  `a_description` TEXT NOT NULL,
  `a_coutry` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`a_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_bd`.`publishing_offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_bd`.`publishing_offices` (
  `id_publishing_office` INT NOT NULL AUTO_INCREMENT,
  `publishing_office_name` VARCHAR(60) NOT NULL,
  `po_adress` VARCHAR(60) NOT NULL,
  `po_number` VARCHAR(30) NOT NULL,
  `po_email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_publishing_office`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_bd`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_bd`.`genres` (
  `g_id` INT NOT NULL AUTO_INCREMENT,
  `g_name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`g_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_bd`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_bd`.`books` (
  `b_id` INT NOT NULL,
  `b_id_publ` INT NOT NULL,
  `genres_g_id` INT NOT NULL,
  `b_name` VARCHAR(80) NOT NULL,
  `b_prod_year` INT NOT NULL,
  `b_rating` FLOAT NOT NULL,
  `b_isbn` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`b_id`),
  INDEX `fk_book_publishing_office1_idx` (`b_id_publ` ASC) VISIBLE,
  INDEX `fk_books_genres1_idx` (`genres_g_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_publishing_office1`
    FOREIGN KEY (`b_id_publ`)
    REFERENCES `library_bd`.`publishing_offices` (`id_publishing_office`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_books_genres1`
    FOREIGN KEY (`genres_g_id`)
    REFERENCES `library_bd`.`genres` (`g_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_bd`.`book_authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_bd`.`book_authors` (
  `author_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  INDEX `fk_book_author_book_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_author_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `library_bd`.`books` (`b_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_book_author_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `library_bd`.`authors` (`a_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_bd`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_bd`.`users` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `u_username` VARCHAR(100) NOT NULL,
  `u_telephone` VARCHAR(20) NOT NULL,
  `u_password` VARCHAR(100) NOT NULL,
  `u_email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`u_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_bd`.`copy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_bd`.`copy` (
  `c_id` INT NOT NULL AUTO_INCREMENT,
  `books_b_id` INT NOT NULL,
  `c_present_num` INT NOT NULL,
  `с_number` INT NOT NULL,
  PRIMARY KEY (`c_id`),
  INDEX `fk_copies_books1_idx` (`books_b_id` ASC) VISIBLE,
  CONSTRAINT `fk_copies_books1`
    FOREIGN KEY (`books_b_id`)
    REFERENCES `library_bd`.`books` (`b_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_bd`.`user_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_bd`.`user_orders` (
  `user_card_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `copies_c_id` INT NOT NULL,
  `date_of_begin` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`user_card_id`),
  INDEX `fk_user_card_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_orders_copies1_idx` (`copies_c_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_card_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `library_bd`.`users` (`u_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_orders_copies1`
    FOREIGN KEY (`copies_c_id`)
    REFERENCES `library_bd`.`copy` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_bd`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_bd`.`reviews` (
  `r_id` INT NOT NULL AUTO_INCREMENT,
  `users_u_id` INT NOT NULL,
  `reviewscol` TEXT NOT NULL,
  PRIMARY KEY (`r_id`),
  INDEX `fk_reviews_users1_idx` (`users_u_id` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_users1`
    FOREIGN KEY (`users_u_id`)
    REFERENCES `library_bd`.`users` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_bd`.`debtors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_bd`.`debtors` (
  `d_id` INT NOT NULL AUTO_INCREMENT,
  `users_u_id` INT NOT NULL,
  `user_orders_user_card_id` INT NOT NULL,
  `sum_of_fine` INT NOT NULL,
  PRIMARY KEY (`d_id`),
  INDEX `fk_debtors_users1_idx` (`users_u_id` ASC) VISIBLE,
  INDEX `fk_debtors_user_orders1_idx` (`user_orders_user_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_debtors_users1`
    FOREIGN KEY (`users_u_id`)
    REFERENCES `library_bd`.`users` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_debtors_user_orders1`
    FOREIGN KEY (`user_orders_user_card_id`)
    REFERENCES `library_bd`.`user_orders` (`user_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_bd`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_bd`.`user_role` (
  `ur_id` INT NOT NULL AUTO_INCREMENT,
  `users_u_id` INT NOT NULL,
  `user_rolecol` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ur_id`),
  INDEX `fk_user_role_users1_idx` (`users_u_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role_users1`
    FOREIGN KEY (`users_u_id`)
    REFERENCES `library_bd`.`users` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
